on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: node:16
    # container: node:17.6.0-alpine
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: npm install
      - run: node app.js